repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^charts/memgraph/templates/
  - id: check-json
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: detect-private-key

- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
  -   id: go-mod-tidy
  -   id: go-vet
  -   id: go-staticcheck-repo-pkg
  -   id: go-fmt
  -   id: go-critic
