//go:build !ignore_autogenerated

/*
Copyright 2024 Memgraph Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
This file is generated by the deepcopy-gen generator. It contains the generated definition
of the DeepCopyObject method for each type defined in the package. This method is necessary
for the structures to implement the runtime.Object interface, which is defined in the API
Machinery Library and the API Machinery expects that all Kind structures will implement
this runtime.Object interface.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Coordinator) DeepCopyInto(out *Coordinator) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Coordinator.
func (in *Coordinator) DeepCopy() *Coordinator {
	if in == nil {
		return nil
	}
	out := new(Coordinator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataItem) DeepCopyInto(out *DataItem) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataItem.
func (in *DataItem) DeepCopy() *DataItem {
	if in == nil {
		return nil
	}
	out := new(DataItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphConfig) DeepCopyInto(out *MemgraphConfig) {
	*out = *in
	out.Data = in.Data
	out.Coordinators = in.Coordinators
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Image = in.Image
	out.Probes = in.Probes
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphConfig.
func (in *MemgraphConfig) DeepCopy() *MemgraphConfig {
	if in == nil {
		return nil
	}
	out := new(MemgraphConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphCoordinatorsConfig) DeepCopyInto(out *MemgraphCoordinatorsConfig) {
	*out = *in
	out.VolumeClaim = in.VolumeClaim
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphCoordinatorsConfig.
func (in *MemgraphCoordinatorsConfig) DeepCopy() *MemgraphCoordinatorsConfig {
	if in == nil {
		return nil
	}
	out := new(MemgraphCoordinatorsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphDataConfig) DeepCopyInto(out *MemgraphDataConfig) {
	*out = *in
	out.VolumeClaim = in.VolumeClaim
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphDataConfig.
func (in *MemgraphDataConfig) DeepCopy() *MemgraphDataConfig {
	if in == nil {
		return nil
	}
	out := new(MemgraphDataConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphHA) DeepCopyInto(out *MemgraphHA) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphHA.
func (in *MemgraphHA) DeepCopy() *MemgraphHA {
	if in == nil {
		return nil
	}
	out := new(MemgraphHA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemgraphHA) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphHAList) DeepCopyInto(out *MemgraphHAList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MemgraphHA, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphHAList.
func (in *MemgraphHAList) DeepCopy() *MemgraphHAList {
	if in == nil {
		return nil
	}
	out := new(MemgraphHAList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemgraphHAList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphHASpec) DeepCopyInto(out *MemgraphHASpec) {
	*out = *in
	if in.Coordinators != nil {
		in, out := &in.Coordinators, &out.Coordinators
		*out = make([]Coordinator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]DataItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Memgraph.DeepCopyInto(&out.Memgraph)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphHASpec.
func (in *MemgraphHASpec) DeepCopy() *MemgraphHASpec {
	if in == nil {
		return nil
	}
	out := new(MemgraphHASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphHAStatus) DeepCopyInto(out *MemgraphHAStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphHAStatus.
func (in *MemgraphHAStatus) DeepCopy() *MemgraphHAStatus {
	if in == nil {
		return nil
	}
	out := new(MemgraphHAStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphProbesConfig) DeepCopyInto(out *MemgraphProbesConfig) {
	*out = *in
	out.Liveness = in.Liveness
	out.Readiness = in.Readiness
	out.Startup = in.Startup
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphProbesConfig.
func (in *MemgraphProbesConfig) DeepCopy() *MemgraphProbesConfig {
	if in == nil {
		return nil
	}
	out := new(MemgraphProbesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeConfig) DeepCopyInto(out *ProbeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeConfig.
func (in *ProbeConfig) DeepCopy() *ProbeConfig {
	if in == nil {
		return nil
	}
	out := new(ProbeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeClaimConfig) DeepCopyInto(out *VolumeClaimConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeClaimConfig.
func (in *VolumeClaimConfig) DeepCopy() *VolumeClaimConfig {
	if in == nil {
		return nil
	}
	out := new(VolumeClaimConfig)
	in.DeepCopyInto(out)
	return out
}
