# permissions for end users to view memgraphhas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: memgraphha-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubernetes-operator
    app.kubernetes.io/part-of: kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: memgraphha-viewer-role
rules:
- apiGroups:
  - memgraph.com
  resources:
  - memgraphhas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - memgraph.com
  resources:
  - memgraphhas/status
  verbs:
  - get
