apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memgraph-kubernetes-operator
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for memgraph.com/v1, Kind: MemgraphHA
##
- apiGroups:
  - memgraph.com
  resources:
  - memgraphhas
  - memgraphhas/status
  - memgraphhas/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- verbs:
  - "*"
  apiGroups:
  - "apps"
  resources:
  - "statefulsets"
- verbs:
  - "*"
  apiGroups:
  - "batch"
  resources:
  - "jobs"
- verbs:
  - "*"
  apiGroups:
  - ""
  resources:
  - "services"

#+kubebuilder:scaffold:rules
