apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: memgraph-kubernetes-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: memgraph-kubernetes-operator
subjects:
- kind: ServiceAccount
  name: memgraph-kubernetes-operator
  namespace: system
