---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memgraph-kubernetes-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memgraph.com
  resources:
  - memgraphhas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memgraph.com
  resources:
  - memgraphhas/finalizers
  verbs:
  - update
- apiGroups:
  - memgraph.com
  resources:
  - memgraphhas/status
  verbs:
  - get
  - patch
  - update
