---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - memgraph.com
  resources:
  - memgraphhas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memgraph.com
  resources:
  - memgraphhas/finalizers
  verbs:
  - update
- apiGroups:
  - memgraph.com
  resources:
  - memgraphhas/status
  verbs:
  - get
  - patch
  - update
