apiVersion: memgraph.com/v1
kind: MemgraphHA
metadata:
  name: memgraphha-sample
spec:
  coordinators:
  - id: "1"
    boltPort: 7687
    managementPort: 10000
    coordinatorPort: 12000
    args:
    - --experimental-enabled=high-availability
    - --coordinator-id=1
    - --coordinator-port=12000
    - --management-port=10000
    - --bolt-port=7687
    - --also-log-to-stderr
    - --log-level=TRACE
    - --coordinator-hostname=memgraph-coordinator-1.default.svc.cluster.local
    - --log-file=/var/log/memgraph/memgraph.log

  - id: "2"
    boltPort: 7687
    managementPort: 10000
    coordinatorPort: 12000
    args:
    - --experimental-enabled=high-availability
    - --coordinator-id=2
    - --coordinator-port=12000

    - --management-port=10000
    - --bolt-port=7687
    - --also-log-to-stderr
    - --log-level=TRACE
    - --coordinator-hostname=memgraph-coordinator-2.default.svc.cluster.local
    - --log-file=/var/log/memgraph/memgraph.log

  - id: "3"
    boltPort: 7687
    managementPort: 10000
    coordinatorPort: 12000
    args:
    - --experimental-enabled=high-availability
    - --coordinator-id=3
    - --coordinator-port=12000
    - --management-port=10000
    - --bolt-port=7687
    - --also-log-to-stderr
    - --log-level=TRACE
    - --coordinator-hostname=memgraph-coordinator-3.default.svc.cluster.local
    - --log-file=/var/log/memgraph/memgraph.log


  data:
  - id: "0"
    boltPort: 7687
    managementPort: 10000
    replicationPort: 20000
    args:
    - --experimental-enabled=high-availability
    - --management-port=10000
    - --bolt-port=7687
    - --also-log-to-stderr
    - --log-level=TRACE
    - --log-file=/var/log/memgraph/memgraph.log

  - id: "1"
    boltPort: 7687
    managementPort: 10000
    replicationPort: 20000
    args:
    - --experimental-enabled=high-availability
    - --management-port=10000
    - --bolt-port=7687
    - --also-log-to-stderr
    - --log-level=TRACE
    - --log-file=/var/log/memgraph/memgraph.log

  memgraph:
    data:
      volumeClaim:
        logPVCClassName: ""
        logPVC: true
        logPVCSize: 256Mi
        storagePVCClassName: ""
        storagePVC: true
        storagePVCSize: 1Gi
    coordinators:
      volumeClaim:
        logPVCClassName: ""
        logPVC: true
        logPVCSize: 256Mi
        storagePVCClassName: ""
        storagePVC: true
        storagePVCSize: 1Gi

    env: # This can be removed I think
      MEMGRAPH_ENTERPRISE_LICENSE: "${MEMGRAPH_ENTERPRISE_LICENSE}"
      MEMGRAPH_ORGANIZATION_NAME: "${MEMGRAPH_ORGANIZATION_NAME}"
    image:
      pullPolicy: IfNotPresent
      repository: memgraph/memgraph
      tag: 2.18.1 # I think we should read this value in controller code.
    probes:
      liveness:
        initialDelaySeconds: 30
        periodSeconds: 10
      readiness:
        initialDelaySeconds: 5
        periodSeconds: 5
      startup:
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10
