//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVar.
func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraArgsSpec) DeepCopyInto(out *ExtraArgsSpec) {
	*out = *in
	if in.Coordinators != nil {
		in, out := &in.Coordinators, &out.Coordinators
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraArgsSpec.
func (in *ExtraArgsSpec) DeepCopy() *ExtraArgsSpec {
	if in == nil {
		return nil
	}
	out := new(ExtraArgsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraEnvSpec) DeepCopyInto(out *ExtraEnvSpec) {
	*out = *in
	if in.Coordinators != nil {
		in, out := &in.Coordinators, &out.Coordinators
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraEnvSpec.
func (in *ExtraEnvSpec) DeepCopy() *ExtraEnvSpec {
	if in == nil {
		return nil
	}
	out := new(ExtraEnvSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelsSpec) DeepCopyInto(out *LabelsSpec) {
	*out = *in
	in.Coordinators.DeepCopyInto(&out.Coordinators)
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelsSpec.
func (in *LabelsSpec) DeepCopy() *LabelsSpec {
	if in == nil {
		return nil
	}
	out := new(LabelsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphCluster) DeepCopyInto(out *MemgraphCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphCluster.
func (in *MemgraphCluster) DeepCopy() *MemgraphCluster {
	if in == nil {
		return nil
	}
	out := new(MemgraphCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemgraphCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphClusterList) DeepCopyInto(out *MemgraphClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MemgraphCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphClusterList.
func (in *MemgraphClusterList) DeepCopy() *MemgraphClusterList {
	if in == nil {
		return nil
	}
	out := new(MemgraphClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MemgraphClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphClusterSpec) DeepCopyInto(out *MemgraphClusterSpec) {
	*out = *in
	if in.Coordinators != nil {
		in, out := &in.Coordinators, &out.Coordinators
		*out = new(int32)
		**out = **in
	}
	if in.DataInstances != nil {
		in, out := &in.DataInstances, &out.DataInstances
		*out = new(int32)
		**out = **in
	}
	out.Image = in.Image
	out.Secrets = in.Secrets
	in.Storage.DeepCopyInto(&out.Storage)
	in.Ports.DeepCopyInto(&out.Ports)
	in.Probes.DeepCopyInto(&out.Probes)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Labels.DeepCopyInto(&out.Labels)
	in.ExtraEnv.DeepCopyInto(&out.ExtraEnv)
	in.ExtraArgs.DeepCopyInto(&out.ExtraArgs)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphClusterSpec.
func (in *MemgraphClusterSpec) DeepCopy() *MemgraphClusterSpec {
	if in == nil {
		return nil
	}
	out := new(MemgraphClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemgraphClusterStatus) DeepCopyInto(out *MemgraphClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemgraphClusterStatus.
func (in *MemgraphClusterStatus) DeepCopy() *MemgraphClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MemgraphClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortsSpec) DeepCopyInto(out *PortsSpec) {
	*out = *in
	if in.BoltPort != nil {
		in, out := &in.BoltPort, &out.BoltPort
		*out = new(int32)
		**out = **in
	}
	if in.ManagementPort != nil {
		in, out := &in.ManagementPort, &out.ManagementPort
		*out = new(int32)
		**out = **in
	}
	if in.ReplicationPort != nil {
		in, out := &in.ReplicationPort, &out.ReplicationPort
		*out = new(int32)
		**out = **in
	}
	if in.CoordinatorPort != nil {
		in, out := &in.CoordinatorPort, &out.CoordinatorPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortsSpec.
func (in *PortsSpec) DeepCopy() *PortsSpec {
	if in == nil {
		return nil
	}
	out := new(PortsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeSpec) DeepCopyInto(out *ProbeSpec) {
	*out = *in
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeSpec.
func (in *ProbeSpec) DeepCopy() *ProbeSpec {
	if in == nil {
		return nil
	}
	out := new(ProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbesSpec) DeepCopyInto(out *ProbesSpec) {
	*out = *in
	in.Coordinators.DeepCopyInto(&out.Coordinators)
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbesSpec.
func (in *ProbesSpec) DeepCopy() *ProbesSpec {
	if in == nil {
		return nil
	}
	out := new(ProbesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesSpec) DeepCopyInto(out *ResourcesSpec) {
	*out = *in
	in.Coordinators.DeepCopyInto(&out.Coordinators)
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesSpec.
func (in *ResourcesSpec) DeepCopy() *ResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(ResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleLabelsSpec) DeepCopyInto(out *RoleLabelsSpec) {
	*out = *in
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StatefulSetLabels != nil {
		in, out := &in.StatefulSetLabels, &out.StatefulSetLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ServiceLabels != nil {
		in, out := &in.ServiceLabels, &out.ServiceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleLabelsSpec.
func (in *RoleLabelsSpec) DeepCopy() *RoleLabelsSpec {
	if in == nil {
		return nil
	}
	out := new(RoleLabelsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleProbesSpec) DeepCopyInto(out *RoleProbesSpec) {
	*out = *in
	in.StartupProbe.DeepCopyInto(&out.StartupProbe)
	in.ReadinessProbe.DeepCopyInto(&out.ReadinessProbe)
	in.LivenessProbe.DeepCopyInto(&out.LivenessProbe)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleProbesSpec.
func (in *RoleProbesSpec) DeepCopy() *RoleProbesSpec {
	if in == nil {
		return nil
	}
	out := new(RoleProbesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleStorageSpec) DeepCopyInto(out *RoleStorageSpec) {
	*out = *in
	if in.LibPVCSize != nil {
		in, out := &in.LibPVCSize, &out.LibPVCSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.LibStorageClassName != nil {
		in, out := &in.LibStorageClassName, &out.LibStorageClassName
		*out = new(string)
		**out = **in
	}
	if in.CreateLogStorageClaim != nil {
		in, out := &in.CreateLogStorageClaim, &out.CreateLogStorageClaim
		*out = new(bool)
		**out = **in
	}
	if in.LogPVCSize != nil {
		in, out := &in.LogPVCSize, &out.LogPVCSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.LogStorageClassName != nil {
		in, out := &in.LogStorageClassName, &out.LogStorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleStorageSpec.
func (in *RoleStorageSpec) DeepCopy() *RoleStorageSpec {
	if in == nil {
		return nil
	}
	out := new(RoleStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretsSpec) DeepCopyInto(out *SecretsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretsSpec.
func (in *SecretsSpec) DeepCopy() *SecretsSpec {
	if in == nil {
		return nil
	}
	out := new(SecretsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	in.Coordinators.DeepCopyInto(&out.Coordinators)
	in.Data.DeepCopyInto(&out.Data)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
